// This header file contains constant for all the display Messages.
#pragma once

#define AGTVIEW_APP "TSAPI Agent View Application"
#define NOT_READY "Not Ready"
#define READY "Ready"
#define BUSY "Busy"
#define IDLE "Idle"
#define ON_CALL "On Call"
#define MONITOR_ADDED "Monitor added to Extension : "
#define AGENT_ID "Agent ID : "
#define AGT_WORK_MODE "Agent Work Mode : "
#define AUTO_IN "Auto In"
#define MANUAL_IN "Manual In"
#define AGT_STATE "Agent State : "
#define NEW_LINE "\r\n"
#define STN_EXTN "Enter the Station Extension."
#define AGT_ID "Enter the Agent ID."
#define AGT_WORKMODE "Select the Agent Work Mode."
#define CTIUSER_AND_CTIPASSWORD "Error: Either CTIUserID or CTIUserPassword is wrong."
#define AGTID_NOT_SUPPORTED "Error: Supplied AgentID is incorrect."
#define DEV_NOT_SUPPORTED "Error: Either\r\n 1. Supplied Station is incorrect, or \r\n 2. Supplied AgentID is incorrect."
#define AGT_OR_STN_NOT_SUPPORTED "Error: Supplied AgentID is incorrect."
#define AGTPASSWORD_NOT_SUPPORTED "Error: Supplied Agent Password is incorrect."
#define STN_NOT_SUPPORTED "Error: Either \r\n 1.Station is out of Service or, \r\n 2. Agent is already logged in "
#define AGT_ALREADY_LOGGED_IN "Invalid Object State , (Agent is already logged in some other station)."
#define ERR_EXTN_NOT_SUPPORTED "Error: Station Extension is not supported."
#define EXTN_OFF "Error : Check Agent might have already Logged In or Extension is Out of Service."
#define AGT_ON_CALL "This sample application does not support Logging in an Agent at a station where a call is already in progress."
#define OPEN_STREAM "Open Stream"
#define ERR_CLOSE_ACSSTREAM "Error while Closing stream."
#define ERR_OPEN_ACSSTREAM "Error while Opening the ACS stream."
#define ERR_AGT_WORKMODE "Error Settings Agent's work Mode."
#define ERR_AGT_SETSTATE "Error while changing state."
#define ERR_REM_MONITOR "Error while Removing monitor."
#define ERR_AGT_NOT_SUPPORTED "Error: Agent ID Not Supported."
#define ERR_ADD_MONITOR "Error: Fail to monitor Device."
#define ERR_QUERY_AGTSTATE "Error While retrieving agent State."
#define ERR_DISCONNECT_CALL "Error while Disconnecting call."
#define ERR_ANSWER_CALL "Error while Answering Call."
#define ERR_CANT_CHANGE_AGT_STATE "Agent State change request to "
#define ACTIVE " is Active "
#define RINGING " is Ringing in Call "
#define TALKING " is Talking in Call "
#define DROPPED " is Dropped from the Call "
#define DEVICE "Device "
#define ENABLE_PENDING " with enablePending flag (enabled)"
#define CHANGE_AGT_STATE "Agent State change request to "
#define ALERT "Alert"
#define INST_ALREADY_RUNNING "An instance of the application is already running. Click OK to terminate"
#define AGT_MANUALLY_LOGOUT "Agent Manually Logout" 
#define INCOMEING_CALL "Incoming Call "
#define FROM " from "
#define TO " To "
#define CALL " Call : "
#define CANT_LOGOUT_AGT "Cannot Logout Agent at this time, Agent is handling a Call "
#define CANT_DISCONT "Disconnecting a held call is not supported, retrieve the call first"
#define CONFER_ESTABLISHED "Conference Call is Established "
#define SP " "
#define CONFERENCING " are Conferencing in Call "
#define DEV_HELD "Device on Hold  : "
#define INVALID " is Invalid"
#define CANT_CHANGE_AGTSTATE "Cannot change Agent State at this time."
#define TRANSFERRED " Transferred"
#define TRANSFERRING_DEV "Transferring Device : "
#define TRANSFERRED_DEV "Transferred Device : "
#define CASE_NOT_SUPPORTED "This Sample Application doesn't support this case. \r\n After clearing the active Call, the application will shutdown"
#define PRIVATE_DATA_NOT_CORRECTLY_NEGOTIATED "Private data is not properly negotiated"
#define CHK_DIALED_NUMBER "Check the Dialed Extension"
#define RETERIEVED " Reterieved "
#define INITIATED " Initiated "
#define SELECT_AGT_STATE "Select Agent State to change "
#define AGT_VIEW "AgentView"
#define ERR "Error"
#define STN_NOT_IN_LIST "Error: CTI User does not have access to the supplied Station"
#define FILE_NOT_FOUND ": File not found in this location. Please copy Settings.ini file to this location and try again."