//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 AvayaCtiService.rc 使用
//
#define IDR_MAINFRAME                   128
#define IDR_AvayaCtiServiceTYPE         130
#define IDD_AvayaCti                    312
#define IDC_AGT_DEVICEID                1002
#define IDC_AGT_LOGINID                 1003
#define IDC_AGT_LOGINPSWD               1004
#define IDC_AGT_AUTO                    1005
#define IDC_AGT_MANUAL                  1007
#define IDC_MESSAGE                     1008
#define IDC_AGT_STATUS                  1009
#define IDC_AGENT_TALK_STATE            1010
#define IDC_AGT_READY                   1011
#define IDC_AGTNOTREADY                 1012
#define IDC_AGENTID_LB                  1012
#define IDC_AGTBUSY                     1013
#define IDC_AGENTID_LB2                 1013
#define IDC_ENABLEPENDING               1014
#define IDC_CALLINGDEVICE_LB            1014
#define IDC_SETAGTSTATE                 1015
#define IDC_CALLEDDEVICE_LB             1015
#define IDC_STN_EXTN                    1016
#define IDC_CALLEDDEVICE_LB2            1016
#define IDC_AGTID                       1017
#define IDC_VIEWSTATE                   1018
#define IDC_AGT_ANSCALL                 1019
#define IDC_AGT_DRPCALL                 1020
#define IDC_DeviceID_LB                 1020
#define IDC_BUTTON4                     1021
#define IDC_ROUTING_SELECT              1021
#define IDC_OpenStream                  1022
#define IDC_Begin                       1023
#define IDC_CLEAR_BTN                   1025
#define IDC_LOGIN_BTN                   1026
#define IDC_Login_GRO                   1027
#define IDC_AGENT_EDIT                  1028
#define IDC_DEVICE_EDIT                 1029
#define IDC_WORKMODE_RADIO1             1030
#define IDC_WORKMODE_RADIO2             1031
#define IDC_LOGOUT_BTN                  1032
#define IDC_AGENTSTATE_GRO              1033
#define IDC_AGENT_EDIT2                 1034
#define IDC_AM_NOTREADY_RADIO           1035
#define IDC_AM_READY_RADIO              1036
#define IDC_STATE_CHANGE_BTN            1037
#define IDC_AGENTSTATE_GRO2             1038
#define IDC_CALLINGDEVICE_EDIT          1039
#define IDC_CALLEDDEVICE_EDIT           1040
#define IDC_AM_BUSY_RADIO               1041
#define IDC_CALL_BTN                    1042
#define IDC_DeviceID_LB2                1043
#define IDC_DEVICE_EDIT2                1044
#define IDC_CHKSTATE_BTN                1045
#define IDC_Monitor_GRO                 1046
#define IDC_DeviceID_LB3                1047
#define IDC_DEVICE_EDIT3                1048
#define IDC_MONITOR_START_BTN           1049
#define IDC_MONITOR_STOP_BTN            1050
#define IDC_DeviceID_LB4                1051
#define IDC_DEVICE_EDIT4                1052
#define IDC_CallID_LB                   1053
#define IDC_CALLID_EDIT                 1054
#define IDC_ANSWER_BTN                  1055
#define IDC_CALLEDDEVICE_EDIT2          1056
#define IDC_QUALITY_GRO                 1057
#define IDC_CDServer_GRO                1058
#define IDC_MonitorCall_btn             1059
#define IDC_DeviceID_LB5                1060
#define IDC_DEVICE_EDIT5                1061
#define IDC_CallID_LB2                  1062
#define IDC_CALLID_EDIT2                1063
#define IDC_CLEARCON_BTN                1064
#define IDC_DeviceID_LB6                1065
#define IDC_DEVICE_EDIT6                1066
#define IDC_CallID_LB3                  1067
#define IDC_CALLID_EDIT3                1068
#define IDC_HOLD_BTN                    1069
#define IDC_DeviceID_LB7                1070
#define IDC_DEVICE_EDIT7                1071
#define IDC_CallID_LB4                  1072
#define IDC_CALLID_EDIT4                1073
#define IDC_CANCELHOLD_BTN              1074
#define IDC_DeviceID_LB8                1075
#define IDC_DEVICE_EDIT8                1076
#define IDC_CallID_LB5                  1077
#define IDC_CALLID_EDIT5                1078
#define IDC_PICKUP_BTN                  1079
#define IDC_DeviceID_LB9                1080
#define IDC_SNAPSHOT_BTN                1081
#define IDC_DEVICE_EDIT9                1082
#define IDC_DeviceID_LB10               1083
#define IDC_DEVICE_EDIT10               1084
#define IDC_PARTICIPATIONTYPE_RADIO1    1085
#define IDC_PARTICIPATIONTYPE_RADIO2    1086
#define IDC_Monitor_GRO2                1087
#define IDC_ACTIVE_RADIO                1088
#define IDC_DeviceID_LB12               1089
#define IDC_CALLEDDEVICE_EDIT3          1090
#define IDC_CONSULT_BTN                 1091
#define IDC_DeviceID_LB13               1092
#define IDC_DEVICE_EDIT12               1093
#define IDC_SNAPSHOT_BTN2               1094
#define IDC_CONF_BTN                    1095
#define IDC_TRANSFER_BTN                1096
#define IDC_HELD_RADIO                  1097
#define IDC_CHECK1                      1098
#define IDC_CHECK2                      1099
#define IDC_BLAKLIST_LB                 1100
#define IDC_ROUTING_EDIT1               1101
#define IDC_ROUTING_INSERT              1102
#define IDC_BUTTON3                     1103
#define IDC_ROUTING_REGISTER            1103
#define IDC_ROUTING_DELETE              1104
#define IDC_ROUTING_GRO                 1105
#define IDC_ROUTING_REGISTERCANCEL      1107
#define IDC_ROUTING_TYPE                1108
#define IDC_ROUTING_UPDATA              1109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
